# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'download_gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ExDownload(object):
    def setupUi(self, ExDownload):
        ExDownload.setObjectName("ExDownload")
        ExDownload.resize(618, 415)
        self.verticalLayout = QtWidgets.QVBoxLayout(ExDownload)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.URLEdit = QtWidgets.QLineEdit(ExDownload)
        self.URLEdit.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Gen Jyuu Gothic Bold")
        font.setBold(True)
        font.setWeight(75)
        self.URLEdit.setFont(font)
        self.URLEdit.setInputMask("")
        self.URLEdit.setObjectName("URLEdit")
        self.horizontalLayout.addWidget(self.URLEdit)
        self.pushButtonClear = QtWidgets.QPushButton(ExDownload)
        font = QtGui.QFont()
        font.setFamily("Gen Jyuu Gothic Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonClear.setFont(font)
        self.pushButtonClear.setObjectName("pushButtonClear")
        self.horizontalLayout.addWidget(self.pushButtonClear)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.FilePathEdit = QtWidgets.QLineEdit(ExDownload)
        self.FilePathEdit.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Gen Jyuu Gothic Bold")
        font.setBold(True)
        font.setWeight(75)
        self.FilePathEdit.setFont(font)
        self.FilePathEdit.setObjectName("FilePathEdit")
        self.horizontalLayout_4.addWidget(self.FilePathEdit)
        self.pushButtonFile = QtWidgets.QPushButton(ExDownload)
        font = QtGui.QFont()
        font.setFamily("Gen Jyuu Gothic Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonFile.setFont(font)
        self.pushButtonFile.setObjectName("pushButtonFile")
        self.horizontalLayout_4.addWidget(self.pushButtonFile)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.pushButtonDownload = QtWidgets.QPushButton(ExDownload)
        font = QtGui.QFont()
        font.setFamily("Gen Jyuu Gothic Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonDownload.setFont(font)
        self.pushButtonDownload.setObjectName("pushButtonDownload")
        self.verticalLayout.addWidget(self.pushButtonDownload)
        self.textBrowser = QtWidgets.QTextBrowser(ExDownload)
        self.textBrowser.setMinimumSize(QtCore.QSize(600, 0))
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButtonClear_2 = QtWidgets.QPushButton(ExDownload)
        font = QtGui.QFont()
        font.setFamily("Gen Jyuu Gothic Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonClear_2.setFont(font)
        self.pushButtonClear_2.setObjectName("pushButtonClear_2")
        self.horizontalLayout_2.addWidget(self.pushButtonClear_2)
        self.pushButtonStop = QtWidgets.QPushButton(ExDownload)
        font = QtGui.QFont()
        font.setFamily("Gen Jyuu Gothic Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonStop.setFont(font)
        self.pushButtonStop.setObjectName("pushButtonStop")
        self.horizontalLayout_2.addWidget(self.pushButtonStop)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(ExDownload)
        QtCore.QMetaObject.connectSlotsByName(ExDownload)

    def retranslateUi(self, ExDownload):
        _translate = QtCore.QCoreApplication.translate
        ExDownload.setWindowTitle(_translate("ExDownload", "ExDownload"))
        self.URLEdit.setText(_translate("ExDownload", "https://exhentai.org/g/1438491/1d30b716e0/"))
        self.URLEdit.setPlaceholderText(_translate("ExDownload", "URL"))
        self.pushButtonClear.setText(_translate("ExDownload", "Clear"))
        self.FilePathEdit.setText(_translate("ExDownload", "G:/ACG/PICTURE/Row"))
        self.FilePathEdit.setPlaceholderText(_translate("ExDownload", "filePath"))
        self.pushButtonFile.setText(_translate("ExDownload", "Path"))
        self.pushButtonDownload.setText(_translate("ExDownload", "Download"))
        self.pushButtonClear_2.setText(_translate("ExDownload", "Clear(Q)"))
        self.pushButtonStop.setText(_translate("ExDownload", "Stop"))

