# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'image_gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MyImage(object):
    def setupUi(self, MyImage):
        MyImage.setObjectName("MyImage")
        MyImage.resize(500, 579)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MyImage.sizePolicy().hasHeightForWidth())
        MyImage.setSizePolicy(sizePolicy)
        MyImage.setMinimumSize(QtCore.QSize(500, 0))
        MyImage.setMaximumSize(QtCore.QSize(500, 579))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(193, 246, 132))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(193, 246, 132))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(193, 246, 132))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        MyImage.setPalette(palette)
        self.verticalLayout = QtWidgets.QVBoxLayout(MyImage)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelImage = MyLabel(MyImage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelImage.sizePolicy().hasHeightForWidth())
        self.labelImage.setSizePolicy(sizePolicy)
        self.labelImage.setMinimumSize(QtCore.QSize(500, 500))
        self.labelImage.setMaximumSize(QtCore.QSize(500, 500))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(75, 168, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(75, 168, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.labelImage.setPalette(palette)
        self.labelImage.setFrameShape(QtWidgets.QFrame.Box)
        self.labelImage.setFrameShadow(QtWidgets.QFrame.Plain)
        self.labelImage.setLineWidth(2)
        self.labelImage.setText("")
        self.labelImage.setScaledContents(False)
        self.labelImage.setAlignment(QtCore.Qt.AlignCenter)
        self.labelImage.setObjectName("labelImage")
        self.verticalLayout.addWidget(self.labelImage)
        self.label_name = QtWidgets.QLabel(MyImage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_name.sizePolicy().hasHeightForWidth())
        self.label_name.setSizePolicy(sizePolicy)
        self.label_name.setMinimumSize(QtCore.QSize(0, 25))
        self.label_name.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Gen Jyuu Gothic P")
        self.label_name.setFont(font)
        self.label_name.setFrameShape(QtWidgets.QFrame.Box)
        self.label_name.setLineWidth(2)
        self.label_name.setText("")
        self.label_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_name.setObjectName("label_name")
        self.verticalLayout.addWidget(self.label_name)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_tag = QtWidgets.QLabel(MyImage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_tag.sizePolicy().hasHeightForWidth())
        self.label_tag.setSizePolicy(sizePolicy)
        self.label_tag.setMinimumSize(QtCore.QSize(0, 25))
        self.label_tag.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Gen Jyuu Gothic Bold")
        font.setBold(True)
        font.setWeight(75)
        self.label_tag.setFont(font)
        self.label_tag.setFrameShape(QtWidgets.QFrame.Box)
        self.label_tag.setLineWidth(2)
        self.label_tag.setText("")
        self.label_tag.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tag.setObjectName("label_tag")
        self.horizontalLayout_2.addWidget(self.label_tag)
        self.label_page = QtWidgets.QLabel(MyImage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_page.sizePolicy().hasHeightForWidth())
        self.label_page.setSizePolicy(sizePolicy)
        self.label_page.setMinimumSize(QtCore.QSize(0, 25))
        self.label_page.setMaximumSize(QtCore.QSize(9999, 25))
        font = QtGui.QFont()
        font.setFamily("Gen Jyuu Gothic Bold")
        font.setBold(True)
        font.setWeight(75)
        self.label_page.setFont(font)
        self.label_page.setFrameShape(QtWidgets.QFrame.Box)
        self.label_page.setLineWidth(2)
        self.label_page.setText("")
        self.label_page.setTextFormat(QtCore.Qt.AutoText)
        self.label_page.setAlignment(QtCore.Qt.AlignCenter)
        self.label_page.setObjectName("label_page")
        self.horizontalLayout_2.addWidget(self.label_page)
        self.horizontalLayout_2.setStretch(0, 9)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_like = QtWidgets.QPushButton(MyImage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_like.sizePolicy().hasHeightForWidth())
        self.pushButton_like.setSizePolicy(sizePolicy)
        self.pushButton_like.setMinimumSize(QtCore.QSize(61, 25))
        self.pushButton_like.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Gen Jyuu Gothic Bold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_like.setFont(font)
        self.pushButton_like.setObjectName("pushButton_like")
        self.horizontalLayout.addWidget(self.pushButton_like)
        self.pushButton_delete = QtWidgets.QPushButton(MyImage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_delete.sizePolicy().hasHeightForWidth())
        self.pushButton_delete.setSizePolicy(sizePolicy)
        self.pushButton_delete.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Gen Jyuu Gothic Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_delete.setFont(font)
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.horizontalLayout.addWidget(self.pushButton_delete)
        self.pushButtonOpen = QtWidgets.QPushButton(MyImage)
        self.pushButtonOpen.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Gen Jyuu Gothic Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonOpen.setFont(font)
        self.pushButtonOpen.setObjectName("pushButtonOpen")
        self.horizontalLayout.addWidget(self.pushButtonOpen)
        self.pushButton_addTag = QtWidgets.QPushButton(MyImage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_addTag.sizePolicy().hasHeightForWidth())
        self.pushButton_addTag.setSizePolicy(sizePolicy)
        self.pushButton_addTag.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Gen Jyuu Gothic Bold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_addTag.setFont(font)
        self.pushButton_addTag.setObjectName("pushButton_addTag")
        self.horizontalLayout.addWidget(self.pushButton_addTag)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(MyImage)
        QtCore.QMetaObject.connectSlotsByName(MyImage)

    def retranslateUi(self, MyImage):
        _translate = QtCore.QCoreApplication.translate
        MyImage.setWindowTitle(_translate("MyImage", "Form"))
        self.pushButton_like.setText(_translate("MyImage", "Like"))
        self.pushButton_delete.setText(_translate("MyImage", "Del"))
        self.pushButtonOpen.setText(_translate("MyImage", "Open"))
        self.pushButton_addTag.setText(_translate("MyImage", "Tag"))

from manga.LittleWidgets import MyLabel
